-- Generated by Oracle SQL Developer Data Modeler 24.3.1.351.0831
--   at:        2025-11-19 13:31:39 EET
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE ALBUM 
    ( 
     ID_Album           INTEGER  NOT NULL , 
     Titlu              VARCHAR2 (50)  NOT NULL , 
     An_Lansare         DATE , 
     GEN_MUZICAL_ID_Gen INTEGER  NOT NULL , 
     ARTIST_ID_Artist   INTEGER  NOT NULL 
    ) 
;

ALTER TABLE ALBUM 
    ADD CONSTRAINT ALBUM_PK PRIMARY KEY ( ID_Album ) ;

CREATE TABLE ARTIST 
    ( 
     ID_Artist INTEGER  NOT NULL , 
     Nume      VARCHAR2 (30)  NOT NULL , 
     Tara      VARCHAR2 (25) 
    ) 
;

ALTER TABLE ARTIST 
    ADD CONSTRAINT ARTIST_PK PRIMARY KEY ( ID_Artist ) ;

CREATE TABLE CLIENT 
    ( 
     ID_Client INTEGER , 
     Nume      VARCHAR2 (40)  NOT NULL , 
     Prenume   VARCHAR2 (40) , 
     Email     VARCHAR2 (60) , 
     Telefon   VARCHAR2 (11)  NOT NULL , 
     CLIENT_ID NUMBER  NOT NULL 
    ) 
;

ALTER TABLE CLIENT 
    ADD CONSTRAINT CLIENT_PK PRIMARY KEY ( CLIENT_ID ) ;

CREATE TABLE COMANDA 
    ( 
     ID_Comanda       INTEGER  NOT NULL , 
     Data_Comanda     DATE , 
     Total            NUMBER  NOT NULL , 
     CLIENT_CLIENT_ID NUMBER  NOT NULL 
    ) 
;

ALTER TABLE COMANDA 
    ADD CONSTRAINT COMANDA_PK PRIMARY KEY ( ID_Comanda ) ;

CREATE TABLE DETALII_COMANDA 
    ( 
     ID_Comanda         INTEGER  NOT NULL , 
     ID_Produs          INTEGER  NOT NULL , 
     Cantitate          INTEGER  NOT NULL , 
     Pret_Unitar        NUMBER  NOT NULL , 
     COMANDA_ID_Comanda INTEGER  NOT NULL , 
     PRODUS_ID_Produs   INTEGER  NOT NULL 
    ) 
;

ALTER TABLE DETALII_COMANDA 
    ADD CONSTRAINT DETALII_COMANDA_PK PRIMARY KEY ( ID_Comanda, ID_Produs ) ;

CREATE TABLE GEN_MUZICAL 
    ( 
     ID_Gen   INTEGER  NOT NULL , 
     Denumire VARCHAR2 (60)  NOT NULL 
    ) 
;

ALTER TABLE GEN_MUZICAL 
    ADD CONSTRAINT GEN_MUZICAL_PK PRIMARY KEY ( ID_Gen ) ;

CREATE TABLE PRODUS 
    ( 
     ID_Produs      INTEGER  NOT NULL , 
     Tip_Format     VARCHAR2 (20)  NOT NULL , 
     Pret           NUMBER  NOT NULL , 
     Stoc           INTEGER  NOT NULL , 
     ALBUM_ID_Album INTEGER  NOT NULL 
    ) 
;

ALTER TABLE PRODUS 
    ADD CONSTRAINT PRODUS_PK PRIMARY KEY ( ID_Produs ) ;

ALTER TABLE ALBUM 
    ADD CONSTRAINT ALBUM_ARTIST_FK FOREIGN KEY 
    ( 
     ARTIST_ID_Artist
    ) 
    REFERENCES ARTIST 
    ( 
     ID_Artist
    ) 
;

ALTER TABLE ALBUM 
    ADD CONSTRAINT ALBUM_GEN_MUZICAL_FK FOREIGN KEY 
    ( 
     GEN_MUZICAL_ID_Gen
    ) 
    REFERENCES GEN_MUZICAL 
    ( 
     ID_Gen
    ) 
;

ALTER TABLE COMANDA 
    ADD CONSTRAINT COMANDA_CLIENT_FK FOREIGN KEY 
    ( 
     CLIENT_CLIENT_ID
    ) 
    REFERENCES CLIENT 
    ( 
     CLIENT_ID
    ) 
;

ALTER TABLE DETALII_COMANDA 
    ADD CONSTRAINT DETALII_COMANDA_COMANDA_FK FOREIGN KEY 
    ( 
     COMANDA_ID_Comanda
    ) 
    REFERENCES COMANDA 
    ( 
     ID_Comanda
    ) 
;

ALTER TABLE DETALII_COMANDA 
    ADD CONSTRAINT DETALII_COMANDA_PRODUS_FK FOREIGN KEY 
    ( 
     PRODUS_ID_Produs
    ) 
    REFERENCES PRODUS 
    ( 
     ID_Produs
    ) 
;

ALTER TABLE PRODUS 
    ADD CONSTRAINT PRODUS_ALBUM_FK FOREIGN KEY 
    ( 
     ALBUM_ID_Album
    ) 
    REFERENCES ALBUM 
    ( 
     ID_Album
    ) 
;

CREATE SEQUENCE CLIENT_CLIENT_ID_SEQ 
START WITH 1 
    NOCACHE 
    ORDER ;

CREATE OR REPLACE TRIGGER CLIENT_CLIENT_ID_TRG 
BEFORE INSERT ON CLIENT 
FOR EACH ROW 
WHEN (NEW.CLIENT_ID IS NULL) 
BEGIN 
    :NEW.CLIENT_ID := CLIENT_CLIENT_ID_SEQ.NEXTVAL; 
END;
/



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             7
-- CREATE INDEX                             0
-- ALTER TABLE                             13
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           1
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          1
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
